name: 🚀 Build & Deploy to Pipra Host

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: 🔍 Debug project structure
        run: |
          pwd
          ls

      - name: 🔑 Create .env
        run: |
          echo "${{ secrets.ENV_FILE }}" > osdel-project/.env

      - name: 🔍 Debug osdel-project
        run: |
          cd osdel-project
          pwd
          ls -la
          cat package.json
          npm run

      - name: 🏗️ Install dependencies
        run: |
          cd osdel-project
          npm ci

      - name: 🏗️ Build project
        run: |
          cd osdel-project
          npm run build

      - name: 📂 Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./osdel-project/dist/
          server-dir: /
          dangerous-clean-slate: false